//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URL_Dumper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("URL_Dumper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon dig {
            get {
                object obj = ResourceManager.GetObject("dig", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diglogo {
            get {
                object obj = ResourceManager.GetObject("diglogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail
        ///mail2
        ///www
        ///ns2
        ///ns1
        ///blog
        ///localhost
        ///m
        ///ftp
        ///mobile
        ///ns3
        ///smtp
        ///search
        ///api
        ///dev
        ///secure
        ///webmail
        ///admin
        ///img
        ///news
        ///sms
        ///test
        ///video
        ///www2
        ///media
        ///static
        ///ads
        ///mail2
        ///beta
        ///wap
        ///dns2
        ///support
        ///pop
        ///my
        ///origin-www
        ///help
        ///newsletter
        ///ns4
        ///upload
        ///mail3
        ///blogs
        ///download
        ///dns1
        ///www3
        ///shop
        ///forum
        ///chat
        ///www1
        ///image
        ///app
        ///tv
        ///dns
        ///services
        ///music
        ///images
        ///game
        ///pay
        ///new
        ///host
        ///www4
        ///service
        ///ad
        ///monitor
        ///web2
        ///wiki
        ///mx1
        ///sports
        ///lists
        ///m1
        ///games
        ///db
        ///m2
        ///business
        ///dns3
        ///ws
        ///counter
        ///travel
        ///photo
        ///gatewa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Subdomain {
            get {
                return ResourceManager.GetString("Subdomain", resourceCulture);
            }
        }
    }
}
